<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size: 10px;
            color: #333;
            padding: 20px;
        }
        
        .header {
            border-bottom: 3px solid #4F46E5;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }
        
        .header h1 {
            color: #4F46E5;
            font-size: 24px;
            margin-bottom: 5px;
        }
        
        .header .subtitle {
            color: #666;
            font-size: 11px;
        }
        
        .meta-info {
            background: #F3F4F6;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        
        .meta-info table {
            width: 100%;
        }
        
        .meta-info td {
            padding: 3px 0;
            font-size: 9px;
        }
        
        .meta-info .label {
            font-weight: bold;
            color: #4B5563;
            width: 120px;
        }
        
        .filters {
            background: #FEF3C7;
            padding: 10px;
            border-left: 3px solid #F59E0B;
            margin-bottom: 20px;
            font-size: 9px;
        }
        
        .filters strong {
            color: #92400E;
        }
        
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        
        table.data-table thead {
            background: #4F46E5;
            color: white;
        }
        
        table.data-table th {
            padding: 8px;
            text-align: left;
            font-size: 10px;
            font-weight: 600;
        }
        
        table.data-table td {
            padding: 6px 8px;
            border-bottom: 1px solid #E5E7EB;
            font-size: 9px;
        }
        
        table.data-table tbody tr:nth-child(even) {
            background: #F9FAFB;
        }
        
        table.data-table tbody tr:hover {
            background: #F3F4F6;
        }
        
        .badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 8px;
            font-weight: 600;
        }
        
        .badge-active {
            background: #D1FAE5;
            color: #065F46;
        }
        
        .badge-inactive {
            background: #FEE2E2;
            color: #991B1B;
        }
        
        .badge-role {
            background: #E0E7FF;
            color: #3730A3;
            margin-right: 3px;
        }
        
        .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #E5E7EB;
            text-align: center;
            font-size: 8px;
            color: #9CA3AF;
        }
        
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ config('app.name') }} - Users Report</h1>
        <div class="subtitle">Comprehensive user listing and details</div>
    </div>
    
    <div class="meta-info">
        <table>
            <tr>
                <td class="label">Generated At:</td>
                <td>{{ $generatedAt->format('F d, Y - H:i:s') }}</td>
                <td class="label">Generated By:</td>
                <td>{{ $generatedBy }}</td>
            </tr>
            <tr>
                <td class="label">Total Users:</td>
                <td>{{ $users->count() }}</td>
                <td class="label">Report Type:</td>
                <td>PDF Export</td>
            </tr>
        </table>
    </div>
    
    @if(!empty(array_filter($filters)))
    <div class="filters">
        <strong>Applied Filters:</strong>
        @if(!empty($filters['search']))
            Search: "{{ $filters['search'] }}" |
        @endif
        @if(!empty($filters['role']))
            Role: {{ ucfirst($filters['role']) }} |
        @endif
        @if(isset($filters['status']))
            Status: {{ ucfirst($filters['status']) }}
        @endif
    </div>
    @endif
    
    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 5%;">ID</th>
                <th style="width: 20%;">Name</th>
                <th style="width: 25%;">Email</th>
                <th style="width: 20%;">Roles</th>
                <th style="width: 10%;">Status</th>
                <th style="width: 10%;">Verified</th>
                <th style="width: 15%;">Created At</th>
            </tr>
        </thead>
        <tbody>
            @forelse($users as $user)
            <tr>
                <td>{{ $user->id }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>
                    @forelse($user->roles as $role)
                        <span class="badge badge-role">{{ $role->name }}</span>
                    @empty
                        <span style="color: #9CA3AF; font-style: italic;">No roles</span>
                    @endforelse
                </td>
                <td>
                    <span class="badge {{ $user->is_active ? 'badge-active' : 'badge-inactive' }}">
                        {{ $user->is_active ? 'Active' : 'Inactive' }}
                    </span>
                </td>
                <td>{{ $user->email_verified_at ? 'Yes' : 'No' }}</td>
                <td>{{ $user->created_at->format('Y-m-d H:i') }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="7" style="text-align: center; padding: 20px; color: #9CA3AF;">
                    No users found matching the criteria.
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>
    
    <div class="footer">
        <p>This report was automatically generated by {{ config('app.name') }}</p>
        <p>Page generated on {{ now()->format('F d, Y \a\t H:i:s') }}</p>
    </div>
</body>
</html>
